# modified from TA-TITOK
experiment:
    project: "titok3D_ll32_vae"
    name: "titok3D_ll32_vae_run1"
    output_dir: "titok3D_ll32_vae_run1"
    max_train_examples: 685_800_000
    save_every: 2000
    eval_every: 1000
    generate_every: 100
    log_every: 10
    log_grad_norm_every: 100
    resume: True

model:
    vq_model:
        quantize_mode: "vq"
        model_type: "titok3DFSQ"
        need_discriminator: True
        token_size: 5
        vit_enc_model_size: "large"
        vit_dec_model_size: "large"
        vit_enc_spatial_patch_size: 16
        vit_enc_temporal_patch_size: 4
        vit_dec_spatial_patch_size: 16
        vit_dec_temporal_patch_size: 4
        num_latent_tokens: 32
        finetune_decoder: false
        is_legacy: false
        use_fsq: True
        fsq_level: [8,8,5,5,5]

losses:
    discriminator_start: 50
    quantizer_weight: 1.0
    discriminator_factor: 1.0
    discriminator_weight: 0.1
    perceptual_loss: "lpips-convnext_s-1.0-0.1"
    perceptual_weight: 1.1
    reconstruction_loss: "l2"
    reconstruction_weight: 1.0
    lecam_regularization_weight: 0.001
    kl_weight: 1e-6
    logvar_init: 0.0

eval:
    method: 'videogpt'
    need_channel_adjustment_fvd: False
    need_channel_adjustment_is: True
    is_splits: 1

dataset:
    params:
        train_path: "datasets/little/train"
        eval_path: "datasets/little/test"
        train_list: "datasets/little/ToyTrainList.txt"
        eval_list: "datasets/little/ToyTestList.txt"        
        fps: 16 

    loader:
        num_workers: 32
        pin_memory: True
        shuffle: True
        drop_last: False

    preprocessing:
        spatial_size: 128
        temporal_size: 16

optimizer:
    name: adamw 
    params:
        learning_rate: 1e-4
        discriminator_learning_rate: 1e-4
        beta1: 0.9
        beta2: 0.999
        weight_decay: 1e-4

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 10
        end_lr: 1e-5

training:
    gradient_accumulation_steps: 1
    per_gpu_batch_size: 1
    mixed_precision: "fp16"
    enable_tf32: True
    enable_wandb: True
    use_ema: True
    seed: 42
    max_train_steps: 650_000
    num_generated_videos: 1
    max_grad_norm: 1.0
    epoch: 2100