# modified from TA-TITOK
experiment:
    project: "titok3D_ll32_vae_UCF_st_long"
    name: "titok3D_ll32_vae_UCF_st_long_run1"
    output_dir: "titok3D_ll32_vae_UCF_st_long_run1"
    max_train_examples: 9537
    save_every: 10000
    eval_every: 10000
    generate_every: 5000
    log_every: 100
    log_grad_norm_every: 500
    resume: True


model:
    vq_model:
        quantize_mode: "vae"
        model_type: "TiTok3DST"
        need_discriminator: True
        token_size: 16
        vit_enc_model_size: "large"
        vit_dec_model_size: "large"
        vit_enc_spatial_patch_size: 16
        vit_enc_temporal_patch_size: 4
        vit_dec_spatial_patch_size: 16
        vit_dec_temporal_patch_size: 4
        num_latent_tokens: 32
        finetune_decoder: false
        is_legacy: false

losses:
    discriminator_start: 600_000
    quantizer_weight: 1.0
    discriminator_factor: 1.0
    discriminator_weight: 0.1
    perceptual_loss: "lpips-convnext_s-1.0-0.1"
    perceptual_weight: 1.1
    reconstruction_loss: "l2"
    reconstruction_weight: 1.0
    lecam_regularization_weight: 0.001
    kl_weight: 1e-6
    logvar_init: 0.0

eval:
    method: 'videogpt'
    need_channel_adjustment_fvd: False
    need_channel_adjustment_is: True
    is_splits: 1

dataset:
    params:
        train_path: "datasets/UCF-101/train"
        eval_path: "datasets/UCF-101/test101"
        train_list: "datasets/UCF-101/trainlist01.txt"
        eval_list: "datasets/UCF-101/testlist-101.txt"        
        fps: 16 

    loader:
        num_workers: 0
        pin_memory: True
        shuffle: True
        drop_last: False

    preprocessing:
        spatial_size: 128
        temporal_size: 16

optimizer:
    name: adamw 
    params:
        learning_rate: 1e-4
        discriminator_learning_rate: 1e-4
        beta1: 0.9
        beta2: 0.999
        weight_decay: 1e-4

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 20_000
        end_lr: 1e-5

training:
    gradient_accumulation_steps: 1
    per_gpu_batch_size: 1
    mixed_precision: "fp16"
    enable_tf32: True
    enable_wandb: True
    use_ema: True
    seed: 42
    max_train_steps: 2002770
    num_generated_videos: 1
    max_grad_norm: 1.0
    epoch: 210    